"""Step 4: golden expected results for tb/tb_nn_core.v.

Reads the weights back from weights/xor_weights.hex (exactly what the ROM is
loaded with), runs the bit-exact integer forward pass, and writes one record
per test input:

  tb/vectors/nn_exp.hex   16-bit words, per case: x[0..N_IN-1], hidden[0..N_HID-1],
                          logit[0..N_OUT-1], pred
  tb/vectors/nn_vectors.vh  `define NN_CASES / NN_STRIDE

Cases: the 4 XOR truth-table inputs, then random real-valued inputs in
[-4, 4) that exercise negative pre-activations (ReLU clamping) and non-trivial
products.

Run from the repo root:  python3 python/gen_nn_vectors.py
"""
import os
import random

from fixedpoint import ONE, DATA_W, to_fixed, to_unsigned, wrap, dot

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
VEC_DIR = os.path.join(ROOT, "tb", "vectors")
N_IN, N_HID, N_OUT = 2, 4, 1


def load_rom(path):
    words = []
    with open(path) as f:
        for line in f:
            tok = line.split("//")[0].strip()
            if tok:
                words.append(wrap(int(tok, 16), DATA_W))
    return words


def forward(rom, xq):
    """Same order and arithmetic as rtl/nn_core.v."""
    b1_base = N_HID * N_IN
    w2_base = b1_base + N_HID
    b2_base = w2_base + N_OUT * N_HID
    hidden = []
    for j in range(N_HID):
        w = rom[j * N_IN:(j + 1) * N_IN] + [rom[b1_base + j]]
        _, r = dot(w, list(xq) + [ONE])
        hidden.append(max(r, 0))
    logits = []
    for o in range(N_OUT):
        w = rom[w2_base + o * N_HID:w2_base + (o + 1) * N_HID] + [rom[b2_base + o]]
        _, r = dot(w, hidden + [ONE])
        logits.append(r)
    pred = int(logits[0] > 0) if N_OUT == 1 else max(range(N_OUT), key=lambda o: logits[o])
    return hidden, logits, pred


def main():
    rom = load_rom(os.path.join(ROOT, "weights", "xor_weights.hex"))
    assert len(rom) == N_HID * N_IN + N_HID + N_OUT * N_HID + N_OUT

    rng = random.Random(42)
    cases = [(x1 * ONE, x2 * ONE) for x1, x2 in [(0, 0), (0, 1), (1, 0), (1, 1)]]
    cases += [(to_fixed(rng.uniform(-4, 4)), to_fixed(rng.uniform(-4, 4))) for _ in range(28)]

    os.makedirs(VEC_DIR, exist_ok=True)
    with open(os.path.join(VEC_DIR, "nn_exp.hex"), "w") as f:
        for n, xq in enumerate(cases):
            hidden, logits, pred = forward(rom, xq)
            words = list(xq) + hidden + logits + [pred]
            f.write(" ".join("%04X" % to_unsigned(w, DATA_W) for w in words))
            f.write("  // case %d: x=(%+.4f, %+.4f) logit=%+.4f pred=%d\n"
                    % (n, xq[0] / ONE, xq[1] / ONE, logits[0] / ONE, pred))
            if n < 4:
                print("x=(%d,%d)  hidden=%s  logit=%+.4f  pred=%d"
                      % (xq[0] // ONE, xq[1] // ONE, [h / ONE for h in hidden],
                         logits[0] / ONE, pred))
    with open(os.path.join(VEC_DIR, "nn_vectors.vh"), "w") as f:
        f.write("// generated by python/gen_nn_vectors.py\n")
        f.write("`define NN_CASES  %d\n`define NN_STRIDE %d\n"
                % (len(cases), N_IN + N_HID + N_OUT + 1))
    print("wrote %d cases to tb/vectors/nn_exp.hex" % len(cases))


if __name__ == "__main__":
    main()
