"""Step 1 + 2: train a 2-4-1 XOR MLP, quantize it to Q8.8, export .mif/.hex.

Network:  x(2) -> Dense(4) -> ReLU -> Dense(1) -> [sigmoid only during training]
In hardware the output neuron's sigmoid is dropped: sigmoid(z) > 0.5 <=> z > 0,
so classification is just the sign bit of the output pre-activation.

Run from the repo root:  python3 python/train_xor.py
"""
import os
import numpy as np

from fixedpoint import (ONE, to_fixed, to_float, dot, to_unsigned, DATA_W, FRAC_W)

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_DIR = os.path.join(ROOT, "weights")

N_IN, N_HID, N_OUT = 2, 4, 1
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=np.float64)
Y = np.array([[0], [1], [1], [0]], dtype=np.float64)


def sigmoid(z):
    return 1.0 / (1.0 + np.exp(-z))


def train(seed, epochs=5000, lr=0.5):
    rng = np.random.default_rng(seed)
    # He init for the ReLU layer
    W1 = rng.normal(0, np.sqrt(2 / N_IN), (N_HID, N_IN))
    b1 = np.zeros(N_HID)
    W2 = rng.normal(0, np.sqrt(1 / N_HID), (N_OUT, N_HID))
    b2 = np.zeros(N_OUT)
    for _ in range(epochs):
        z1 = X @ W1.T + b1
        h = np.maximum(z1, 0)
        z2 = h @ W2.T + b2
        p = sigmoid(z2)
        # binary cross-entropy gradient w.r.t. z2 is (p - y)
        dz2 = (p - Y) / len(X)
        dW2 = dz2.T @ h
        db2 = dz2.sum(0)
        dh = dz2 @ W2
        dz1 = dh * (z1 > 0)
        dW1 = dz1.T @ X
        db1 = dz1.sum(0)
        W1 -= lr * dW1; b1 -= lr * db1
        W2 -= lr * dW2; b2 -= lr * db2
    p = sigmoid(np.maximum(X @ W1.T + b1, 0) @ W2.T + b2)
    loss = -np.mean(Y * np.log(p + 1e-12) + (1 - Y) * np.log(1 - p + 1e-12))
    return (W1, b1, W2, b2), p, loss


def fixed_forward(qW1, qb1, qW2, qb2, x_bits):
    """Integer forward pass exactly as the hardware will do it (built from MAC ops).

    Bias trick: each neuron's bias is fed to the MAC as one extra term (bias * 1.0),
    so the MAC needs no separate bias port.
    """
    xq = [x * ONE for x in x_bits]                     # inputs are 0.0 / 1.0 in Q8.8
    hidden = []
    for j in range(N_HID):
        _, r = dot(list(qW1[j]) + [qb1[j]], xq + [ONE])
        hidden.append(max(r, 0))                       # ReLU = sign-bit mux
    _, z = dot(list(qW2[0]) + [qb2[0]], hidden + [ONE])
    return hidden, z


def write_mif(path, words, comments):
    with open(path, "w") as f:
        f.write("-- XOR MLP weights, Q%d.%d signed, generated by python/train_xor.py\n"
                % (DATA_W - FRAC_W, FRAC_W))
        f.write("WIDTH=%d;\nDEPTH=%d;\n\nADDRESS_RADIX=UNS;\nDATA_RADIX=HEX;\n\n"
                % (DATA_W, len(words)))
        f.write("CONTENT BEGIN\n")
        for addr, (w, c) in enumerate(zip(words, comments)):
            f.write("    %d : %04X;  -- %s\n" % (addr, to_unsigned(w, DATA_W), c))
        f.write("END;\n")


def write_hex(path, words, comments):
    # $readmemh format, one word per line. Quartus loads this file too, so it
    # carries no comments; the .mif has the annotated copy.
    with open(path, "w") as f:
        for w in words:
            f.write("%04X\n" % to_unsigned(w, DATA_W))


def main():
    # Deterministic: take the first seed that converges (ReLU nets can get stuck
    # with dead units on XOR, which is itself a nice thing to know about).
    for seed in range(100):
        params, p, loss = train(seed)
        if np.all((p > 0.5) == (Y > 0.5)) and loss < 0.05:
            break
    else:
        raise RuntimeError("no seed converged")
    W1, b1, W2, b2 = params
    print("seed %d, final BCE loss %.5f" % (seed, loss))

    qW1 = [[to_fixed(v) for v in row] for row in W1]
    qb1 = [to_fixed(v) for v in b1]
    qW2 = [[to_fixed(v) for v in row] for row in W2]
    qb2 = [to_fixed(v) for v in b2]

    all_f = np.concatenate([W1.ravel(), b1, W2.ravel(), b2])
    all_q = np.array([to_float(q) for q in
                      sum(qW1, []) + qb1 + sum(qW2, []) + qb2])
    print("weight range [%.3f, %.3f], max quantization error %.5f (LSB = %.5f)"
          % (all_f.min(), all_f.max(), np.abs(all_f - all_q).max(), 1 / ONE))

    print("\n x1 x2 | float p  | fixed z2 (Q8.8)      | class | expect")
    ok = True
    for i, (x1, x2) in enumerate(X.astype(int)):
        _, z = fixed_forward(qW1, qb1, qW2, qb2, [x1, x2])
        cls = int(z > 0)
        ok &= cls == int(Y[i, 0])
        print("  %d  %d | %.4f   | %6d (%+8.4f)    |   %d   |   %d"
              % (x1, x2, p[i, 0], z, to_float(z), cls, int(Y[i, 0])))
    assert ok, "quantized network misclassifies XOR"
    print("quantized network classifies all 4 XOR inputs correctly")

    # Memory map (one 16-bit word per address):
    #   0..7   W1[j][i]  row-major, j = hidden neuron, i = input
    #   8..11  b1[j]
    #   12..15 W2[0][j]
    #   16     b2[0]
    words, comments = [], []
    for j in range(N_HID):
        for i in range(N_IN):
            words.append(qW1[j][i]); comments.append("W1[%d][%d] = %+.4f" % (j, i, W1[j, i]))
    for j in range(N_HID):
        words.append(qb1[j]); comments.append("b1[%d]    = %+.4f" % (j, b1[j]))
    for j in range(N_HID):
        words.append(qW2[0][j]); comments.append("W2[0][%d] = %+.4f" % (j, W2[0, j]))
    words.append(qb2[0]); comments.append("b2[0]    = %+.4f" % b2[0])

    os.makedirs(OUT_DIR, exist_ok=True)
    write_mif(os.path.join(OUT_DIR, "xor_weights.mif"), words, comments)
    write_hex(os.path.join(OUT_DIR, "xor_weights.hex"), words, comments)
    np.savez(os.path.join(OUT_DIR, "xor_weights_float.npz"), W1=W1, b1=b1, W2=W2, b2=b2)
    print("\nwrote weights/xor_weights.mif, weights/xor_weights.hex (%d words)" % len(words))


if __name__ == "__main__":
    main()
