// ---------------------------------------------------------------------------
// tb_nn_core.v  -  self-checking testbench for the full forward pass
//
// For every case in tb/vectors/nn_exp.hex (generated by python/gen_nn_vectors.py
// from the same weight file the ROM loads), pulse start, wait for done, and
// compare every hidden activation, the logit and the predicted class bit-for-bit.
// Also measures latency in clock cycles.
// ---------------------------------------------------------------------------
`timescale 1ns / 1ps
`include "nn_vectors.vh"

module tb_nn_core;

    parameter DATA_W   = 16;
    parameter N_IN     = 2;
    parameter N_HID    = 4;
    parameter N_OUT    = 1;
    parameter VEC_DIR  = "../tb/vectors/";
    parameter HEX_FILE = "../weights/xor_weights.hex";
    parameter TIMEOUT  = 1000;

    reg clk = 1'b0;
    reg rst_n = 1'b0;
    always #10 clk = ~clk;          // 50 MHz

    reg                        start = 1'b0;
    reg  [N_IN*DATA_W-1:0]     x_flat = 0;
    wire                       busy, done;
    wire [N_HID*DATA_W-1:0]    hidden_flat;
    wire [N_OUT*DATA_W-1:0]    logits_flat;
    wire                       pred;

    nn_core #(.N_IN(N_IN), .N_HID(N_HID), .N_OUT(N_OUT), .HEX_FILE(HEX_FILE)) dut (
        .clk(clk), .rst_n(rst_n),
        .start(start), .x_flat(x_flat), .x_addr(), .x_data({DATA_W{1'b0}}),
        .busy(busy), .done(done),
        .hidden_flat(hidden_flat), .logits_flat(logits_flat), .pred(pred)
    );

    reg [DATA_W-1:0] vec [0:`NN_CASES*`NN_STRIDE-1];

    integer c, j, base, cycles, n_errors;
    reg signed [DATA_W-1:0] got, exp;

    task check;
        input [8*16-1:0]   name;
        input integer      idx;
        input [DATA_W-1:0] g;
        input [DATA_W-1:0] e;
        begin
            if (g !== e) begin
                $display("FAIL case %0d %0s[%0d]: got %h (%f) expected %h (%f)",
                         c, name, idx, g, $itor($signed(g)) / 256.0,
                         e, $itor($signed(e)) / 256.0);
                n_errors = n_errors + 1;
            end
        end
    endtask

    initial begin
        $readmemh({VEC_DIR, "nn_exp.hex"}, vec);
        n_errors = 0;
        repeat (3) @(posedge clk);
        rst_n <= 1'b1;
        @(posedge clk);

        for (c = 0; c < `NN_CASES; c = c + 1) begin
            base = c * `NN_STRIDE;
            for (j = 0; j < N_IN; j = j + 1)
                x_flat[j*DATA_W +: DATA_W] <= vec[base + j];
            start <= 1'b1;
            @(posedge clk);
            start <= 1'b0;
            cycles = 1;
            while (!done && cycles < TIMEOUT) begin
                @(posedge clk);
                cycles = cycles + 1;
            end
            if (!done) begin
                $display("FAIL case %0d: no done after %0d cycles", c, TIMEOUT);
                n_errors = n_errors + 1;
            end
            #1;   // let nonblocking updates from this edge settle before sampling

            for (j = 0; j < N_HID; j = j + 1)
                check("hidden", j, hidden_flat[j*DATA_W +: DATA_W], vec[base + N_IN + j]);
            for (j = 0; j < N_OUT; j = j + 1)
                check("logit", j, logits_flat[j*DATA_W +: DATA_W], vec[base + N_IN + N_HID + j]);
            check("pred", 0, {{(DATA_W-1){1'b0}}, pred}, vec[base + N_IN + N_HID + N_OUT]);

            if (c < 4)
                $display("x=(%0d,%0d)  logit=%f  pred=%0d  (%0d cycles)",
                         vec[base] >> 8, vec[base + 1] >> 8,
                         $itor($signed(logits_flat[DATA_W-1:0])) / 256.0, pred, cycles);
            @(posedge clk);
        end

        $display("--------------------------------------------------");
        if (n_errors == 0)
            $display("TEST PASSED: %0d inferences matched the Python model, %0d cycles each",
                     `NN_CASES, cycles);
        else
            $display("TEST FAILED: %0d errors", n_errors);
        $display("--------------------------------------------------");
        $finish;
    end

endmodule
